-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 96fb7fa
    hooks:
    -   id: check-merge-conflict
    -   id: trailing-whitespace
        args:
        - --no-markdown-linebreak-ext
    -   id: check-yaml
-   repo: git://github.com/Lucas-C/pre-commit-hooks
    sha: v1.0.0
    hooks:
    -   id: remove-crlf
    -   id: remove-tabs
-   repo: https://github.com/Lucas-C/pre-commit-hooks-html
    sha: v1.1.0
    hooks:
    -   id: htmlhint
    -   id: htmllint
    -   id: validate-html
